### ISSUE TITLE
yast network module conflicts with systemd preset?

### ISSUE THREAD

**Issue by JonathanKang** [yast/yast-network#1013]
Found when implementing this [feature](https://bugzilla.suse.com/show_bug.cgi?id=1038403). The main problem is whether NetworkManager should be enabled is decided in yast network module. While systemd presets tries to enable NetworkManager in any situation.
Do you think we should ignore the systemd preset? Or some changes should be made in yast network module to disable NetworkManager when it's not used, even systemd presets enable it.

**Comment by dgdavid** [comment]
> Do you think we should ignore the systemd preset? 

Honestly, this doesn't seem to be a decision for the YaST team at this time since it is actually up to the maintainers of systemd presets, NetworkManager, and/or wicked.

> Or some changes should be made in yast network module to disable NetworkManager when it's not used, even systemd presets enable it.

We can warning to the user when both services, NetworkManager and wicked, are running and maybe offer the option to disable one of them. Let's see.

Anyway, there is an open reported bug at https://bugzilla.opensuse.org/show_bug.cgi?id=1141433, which is also in our tasks queue.

So, since we have both things tracked at bugzilla, I'm going to close this issue for now. Please, feel free to add supplementary information if needed.

Thanks·
